# Generated by Django 5.0.6 on 2024-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
