# Generated by Django 5.0.6 on 2024-06-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_useraccount_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_admin',
        ),
    ]
